baseURL = "https://stock.informationhot.kr/"
languageCode = "ko-KR"
title = "캔들트렌드 - 주식정보 블로그"
theme = "congo"
paginate = 20

[params]
  colorScheme = "avocado"
  defaultAppearance = "light"
  autoSwitchAppearance = true
  showScrollToTop = true
  favicon = "/images/candle-favicon.png"
  
  [params.assets]
    customCSS = ["css/custom.css"]
  
  [params.homepage]
    layout = "page"
    showRecent = true
    recentLimit = 50

  [params.list]
    showBreadcrumbs = true
    showTableOfContents = false
    groupByYear = false

  [params.article]
    showDate = true
    showReadingTime = true
    showTaxonomies = true
    showTableOfContents = true
    showRelatedContent = true

  [params.author]
    name = "캔들트렌드"

[menu]
  [[menu.main]]
    name = "홈"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "전체글"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "IPO"
    url = "/categories/ipo/"
    weight = 3
  [[menu.main]]
    name = "주식분석"
    url = "/categories/주식분석/"
    weight = 4

[taxonomies]
  category = "categories"
  tag = "tags"
